
//
// designTokens+EnumApp.swift
//

// Do not edit directly
// Generated on Thu, 22 Jun 2023 10:50:23 GMT


import UIKit

public enum StyleDictionaryEnumApp {
    public static let mchAppBodyBodyTextFontSize = 17
    public static let mchAppBodyBodyTextFontWeight = 400
    public static let mchAppBodyBodyTextLetterSpacing = 0
    public static let mchAppBodyBodyTextLineHeight = 22
    public static let mchAppBodyBodyTextParagraphIndent = 0
    public static let mchAppBodyBodyTextParagraphSpacing = 0
    public static let mchAppBodyBodyTextTextCase = "none"
    public static let mchAppBodyBodyTextTextDecoration = "none"
    public static let mchAppBodyButtonFontSize = 14
    public static let mchAppBodyButtonFontWeight = 700
    public static let mchAppBodyButtonLetterSpacing = 0
    public static let mchAppBodyButtonLineHeight = 18
    public static let mchAppBodyButtonParagraphIndent = 0
    public static let mchAppBodyButtonParagraphSpacing = 0
    public static let mchAppBodyButtonTextCase = "uppercase"
    public static let mchAppBodyButtonTextDecoration = "none"
    public static let mchAppBodyCalloutFontSize = 16
    public static let mchAppBodyCalloutFontWeight = 700
    public static let mchAppBodyCalloutLetterSpacing = 0
    public static let mchAppBodyCalloutLineHeight = 21
    public static let mchAppBodyCalloutParagraphIndent = 0
    public static let mchAppBodyCalloutParagraphSpacing = 0
    public static let mchAppBodyCalloutTextCase = "capitalize"
    public static let mchAppBodyCalloutTextDecoration = "none"
    public static let mchAppBodyCaption1FontSize = 12
    public static let mchAppBodyCaption1FontWeight = 700
    public static let mchAppBodyCaption1LetterSpacing = 0
    public static let mchAppBodyCaption1LineHeight = 16
    public static let mchAppBodyCaption1ParagraphIndent = 0
    public static let mchAppBodyCaption1ParagraphSpacing = 0
    public static let mchAppBodyCaption1TextCase = "none"
    public static let mchAppBodyCaption1TextDecoration = "none"
    public static let mchAppBodyCaption2FontSize = 11
    public static let mchAppBodyCaption2FontWeight = 400
    public static let mchAppBodyCaption2LetterSpacing = 0
    public static let mchAppBodyCaption2LineHeight = 13
    public static let mchAppBodyCaption2ParagraphIndent = 0
    public static let mchAppBodyCaption2ParagraphSpacing = 0
    public static let mchAppBodyCaption2TextCase = "none"
    public static let mchAppBodyCaption2TextDecoration = "none"
    public static let mchAppBodyFootnoteFontSize = 13
    public static let mchAppBodyFootnoteFontWeight = 400
    public static let mchAppBodyFootnoteLetterSpacing = 0
    public static let mchAppBodyFootnoteLineHeight = 18
    public static let mchAppBodyFootnoteParagraphIndent = 0
    public static let mchAppBodyFootnoteParagraphSpacing = 0
    public static let mchAppBodyFootnoteTextCase = "none"
    public static let mchAppBodyFootnoteTextDecoration = "none"
    public static let mchAppElevations011Blur = 4
    public static let mchAppElevations011Color = UIColor(red: 0.114, green: 0.137, blue: 0.153, alpha: 0.10196078431372549)
    public static let mchAppElevations011Spread = 0
    public static let mchAppElevations011Type = "dropShadow"
    public static let mchAppElevations011X = 0
    public static let mchAppElevations011Y = 1
    public static let mchAppElevations012Blur = 4
    public static let mchAppElevations012Color = UIColor(red: 0.114, green: 0.137, blue: 0.153, alpha: 0.10196078431372549)
    public static let mchAppElevations012Spread = 0
    public static let mchAppElevations012Type = "dropShadow"
    public static let mchAppElevations012X = 0
    public static let mchAppElevations012Y = 0
    public static let mchAppElevations021Blur = 8
    public static let mchAppElevations021Color = UIColor(red: 0.114, green: 0.137, blue: 0.153, alpha: 0.10196078431372549)
    public static let mchAppElevations021Spread = 0
    public static let mchAppElevations021Type = "dropShadow"
    public static let mchAppElevations021X = 0
    public static let mchAppElevations021Y = 4
    public static let mchAppElevations022Blur = 4
    public static let mchAppElevations022Color = UIColor(red: 0.114, green: 0.137, blue: 0.153, alpha: 0.10196078431372549)
    public static let mchAppElevations022Spread = 0
    public static let mchAppElevations022Type = "dropShadow"
    public static let mchAppElevations022X = 0
    public static let mchAppElevations022Y = 2
    public static let mchAppElevations031Blur = 16
    public static let mchAppElevations031Color = UIColor(red: 0.114, green: 0.137, blue: 0.153, alpha: 0.10196078431372549)
    public static let mchAppElevations031Spread = 0
    public static let mchAppElevations031Type = "dropShadow"
    public static let mchAppElevations031X = 0
    public static let mchAppElevations031Y = 8
    public static let mchAppElevations032Blur = 8
    public static let mchAppElevations032Color = UIColor(red: 0.114, green: 0.137, blue: 0.153, alpha: 0.10196078431372549)
    public static let mchAppElevations032Spread = 0
    public static let mchAppElevations032Type = "dropShadow"
    public static let mchAppElevations032X = 0
    public static let mchAppElevations032Y = 4
    public static let mchAppHeadingsH1FontSize = 28
    public static let mchAppHeadingsH1FontWeight = 700
    public static let mchAppHeadingsH1LetterSpacing = 0
    public static let mchAppHeadingsH1LineHeight = 34
    public static let mchAppHeadingsH1ParagraphIndent = 0
    public static let mchAppHeadingsH1ParagraphSpacing = 0
    public static let mchAppHeadingsH1TextCase = "none"
    public static let mchAppHeadingsH1TextDecoration = "none"
    public static let mchAppHeadingsH2FontSize = 22
    public static let mchAppHeadingsH2FontWeight = 700
    public static let mchAppHeadingsH2LetterSpacing = 0
    public static let mchAppHeadingsH2LineHeight = 28
    public static let mchAppHeadingsH2ParagraphIndent = 0
    public static let mchAppHeadingsH2ParagraphSpacing = 0
    public static let mchAppHeadingsH2TextCase = "none"
    public static let mchAppHeadingsH2TextDecoration = "none"
    public static let mchAppHeadingsH3FontSize = 20
    public static let mchAppHeadingsH3FontWeight = 700
    public static let mchAppHeadingsH3LetterSpacing = 0
    public static let mchAppHeadingsH3LineHeight = 25
    public static let mchAppHeadingsH3ParagraphIndent = 0
    public static let mchAppHeadingsH3ParagraphSpacing = 0
    public static let mchAppHeadingsH3TextCase = "none"
    public static let mchAppHeadingsH3TextDecoration = "none"
    public static let mchAppHeadingsH4FontSize = 17
    public static let mchAppHeadingsH4FontWeight = 700
    public static let mchAppHeadingsH4LetterSpacing = 0
    public static let mchAppHeadingsH4LineHeight = 22
    public static let mchAppHeadingsH4ParagraphIndent = 0
    public static let mchAppHeadingsH4ParagraphSpacing = 0
    public static let mchAppHeadingsH4TextCase = "none"
    public static let mchAppHeadingsH4TextDecoration = "none"
    public static let mchAppHeadingsLargeTitleFontSize = 34
    public static let mchAppHeadingsLargeTitleFontWeight = 700
    public static let mchAppHeadingsLargeTitleLetterSpacing = 0
    public static let mchAppHeadingsLargeTitleLineHeight = 41
    public static let mchAppHeadingsLargeTitleParagraphIndent = 0
    public static let mchAppHeadingsLargeTitleParagraphSpacing = 0
    public static let mchAppHeadingsLargeTitleTextCase = "none"
    public static let mchAppHeadingsLargeTitleTextDecoration = "none"
    public static let mchAppHeadingsSubheadFontSize = 15
    public static let mchAppHeadingsSubheadFontWeight = 400
    public static let mchAppHeadingsSubheadLetterSpacing = 0
    public static let mchAppHeadingsSubheadLineHeight = 20
    public static let mchAppHeadingsSubheadParagraphIndent = 0
    public static let mchAppHeadingsSubheadParagraphSpacing = 0
    public static let mchAppHeadingsSubheadTextCase = "none"
    public static let mchAppHeadingsSubheadTextDecoration = "none"
    public static let mchFontSize0 = 11
    public static let mchFontSize1 = 12
    public static let mchFontSize10 = 34
    public static let mchFontSize2 = 13
    public static let mchFontSize3 = 14
    public static let mchFontSize4 = 15
    public static let mchFontSize5 = 16
    public static let mchFontSize6 = 17
    public static let mchFontSize7 = 20
    public static let mchFontSize8 = 22
    public static let mchFontSize9 = 28
    public static let mchFontWeightsArtBaselHeadline0 = 700
    public static let mchFontWeightsArtBaselText1 = 700
    public static let mchFontWeightsArtBaselText2 = 400
    public static let mchLetterSpacing0 = 0
    public static let mchLineHeights0 = 41
    public static let mchLineHeights1 = 34
    public static let mchLineHeights2 = 28
    public static let mchLineHeights3 = 25
    public static let mchLineHeights4 = 22
    public static let mchLineHeights5 = 20
    public static let mchLineHeights6 = 21
    public static let mchLineHeights7 = 18
    public static let mchLineHeights8 = 16
    public static let mchLineHeights9 = 13
    public static let mchParagraphIndent0 = 0
    public static let mchParagraphSpacing0 = 0
    public static let mchTextCaseCapitalize = "capitalize"
    public static let mchTextCaseLowercase = "lowercase"
    public static let mchTextCaseNone = "none"
    public static let mchTextCaseUppercase = "uppercase"
    public static let mchTextDecorationNone = "none"
}
